import type { NextPage } from "next";
import Head from "next/head";
import { appTitle, greetMessage } from "../services/strings";
import styles from "../styles/Home.module.css";
import { Player } from "@lottiefiles/react-lottie-player";
import { Box, Fab } from "@mui/material";
import { Menu, Add } from "@mui/icons-material";
import { NextRouter, useRouter } from "next/router";
import React, { CSSProperties, useState } from "react";

const fabStyle: CSSProperties = {
  margin: 0,
  top: "auto",
  right: 20,
  bottom: 20,
  left: "auto",
  position: "fixed",
};

const btnStyle: CSSProperties = {
  backgroundColor: "#A85CF9",
  color: "#fff",
};

const Home: NextPage = () => {
  const router: NextRouter = useRouter();

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>{appTitle}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <h1>{greetMessage}</h1>

          <div>
            <Player
              autoplay
              loop
              style={{ height: "400px" }}
              src="https://assets7.lottiefiles.com/packages/lf20_6ft9bypa.json"
            />
          </div>

          <p>
            நம் தாய்மொழியாம் தமிழ்மொழியின் தொன்மையை பேணிக்காக்க நிறைய அறிவியல்
            பொறியியல் தொழில்நுட்ப சொற்களை தமிழில் உருவாக்கி செயல்களை
            மேற்கொள்ளும் போது அறிவியல்,தொழில்நுட்பச் சொற்கள் பெருகப் பெருக நம்
            மொழியும் வளர்ந்து சிறந்து உயர்வு பெறும் என்ற வகையில் இந்த வலைதளம்
            உருவாக்கப்பட்டுள்ளது. பொறியில் தொழில்நுட்பத்தில் உள்ள ஆங்கில
            வார்த்தைக்கு நிகரான நிறைய சொற்கள் புதிதாக உருவாக்க ஓர் சிறிய
            முயற்சியாக இந்த வலைதளம் அமையும். மொழி வளர்ச்சி பெருகும் வகையில்
            மொழிப்பெயர்ப்பு புலமையாளர்கள், பொதுமக்கள்,அறிஞர்கள் மாணவர்கள்
            உள்ளிட்ட அனைவருக்கும் பயன்படும் வகையிலும் அனைவரும் தங்களுக்கு
            தெரிந்த சொற்களை அறிமுகப்படுத்தி அதை சரியாக இருக்கும் போது தங்களால்
            உருவாக்கப்பட்ட அந்த சொற்கள் இங்கு பதிவேற்றம் செய்யப்படும். தொன்மையான
            நம் மொழியானது அனைத்து அறிவியல் பொறியியல் தொழில்நுட்ப துறைகளுக்குமான
            கலைச்சொற்களைத் தன் சொல்வளத்திலிருந்தே உருவாக்கிக்கொள்ளும் ஆற்றல்
            வாய்ந்ததுமான தமிழ்மொழியில், சொல்லின் தெளிவாகப் புரிந்துகொள்ளுவதற்கு
            ஓர் அடிப்படை தளமாக இது அமையும். அனைவரும் ஒன்றிணைவோம்! கலைச்சொற்களை
            உருவாக்குவோம்!!
          </p>
        </main>

        <footer className={styles.footer}></footer>
      </div>
      <Box style={fabStyle}>
        <Fab
          variant="extended"
          style={btnStyle}
          onClick={() => router.push("/addnew")}
        >
          <Add sx={{ mr: 1 }} />
          சேர்க்க
        </Fab>
      </Box>
    </>
  );
};

export default Home;
